# Get twitter follower's info of a list of IDs

In [1]:
import csv
import os
import json
import tweepy
import requests
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
import numpy as np

In [2]:
#auth
consumer_key = 'xxxxxxxxxxxxxxx'
consumer_secret = 'xxxxxxxxxxxxxx'
access_token = 'xxxxxxxxxxxxxx'
access_token_secret = 'xxxxxxxxxxxxxxxxxxxx'

# OAuthHandler using the keys and tokens
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

# authentication api
api = tweepy.API(auth, wait_on_rate_limit=True)

In [3]:
#test
user_info = api.get_user('MultiplierMXX')._json
follower = user_info['followers_count']
#total_tweets = user_info['statuses_count']
print (follower)

3937

In [4]:
#insert a list of twitter ids
id_list = ['LidyaShian','fella_techno','SumitKumar049','Danish18197485','AshishP13450984','Mohce9',
           'Rezaghani9','akatds','jenosinauot','marisacang','karakterpasif','Cryptoupdate02','sky_blues09',
           'GalangInterist1','ARIORIZQY','abeedeak','lndroper']

#create an empty list to store followers
followers = []

#print(user_info)

#looping
for id in id_list:
    try:
        user_info = api.get_user(id)._json
        follower = user_info['followers_count']
        followers.append(follower)
    except Exception as e:
        followers.append('na')
    continue
print (id_list) #optional
print (followers)

['LidyaShian', 'fella_techno', 'SumitKumar049', 'Danish18197485', 'AshishP13450984', 'Mohce9', 'Rezaghani9', 'akatds', 'jenosinauot', 'marisacang', 'karakterpasif', 'Cryptoupdate02', 'sky_blues09', 'GalangInterist1', 'ARIORIZQY', 'abeedeak', 'lndroper']
[24, 43, 170, 248, 55, 3, 12, 14334, 50, 5924, 244, 54, 134, 99, 127, 242, 22]

In [5]:
#create a dataframe for easier look
dict = {'id' : id_list, 'followers' : followers}
df_twitter = pd.DataFrame(dict)
df_twitter

                 id  followers
0        LidyaShian         24
1      fella_techno         43
2     SumitKumar049        170
3    Danish18197485        248
4   AshishP13450984         55
5            Mohce9          3
6        Rezaghani9         12
7            akatds      14334
8       jenosinauot         50
9        marisacang       5924
10    karakterpasif        244
11   Cryptoupdate02         54
12      sky_blues09        134
13  GalangInterist1         99
14        ARIORIZQY        127
15         abeedeak        242
16         lndroper         22

In [6]:
#another list 
id_list2 = ['autofarmnetwork', 'bDollar_Fi', 'beefyfinance', 'bitgrit_global', 'bloqinc', 'BondlyFinance', 
            'CafeSwapFinance','crowfinance', 'Crypto_novae', 'dao_duck', 'DeFi_Absorber',
            'deflectprotocol', 'ethalend', 'ezDeFi', 'financeGoose', 'flarefinance', 'goldfinch_fi', 
            'InverseProject', 'Kylin_Network', 'Liquid_Global', 'marginswap', 'Mdextech', 'mimoprotocol',
            'NftHero', 'overlinenetwork', 'paid_network', 'PandaYield', 'QuiverX5', 'rigelprotocol',
            'shadows_defi', 'sparkpointio', 'stakewise_io', 'Team_Hedget', 'TheDaoMaker', 'tixlfinance',
           'UnidoEP', 'UNNFinance', 'unstoppableweb', 'xdefilab','xendfinance', 'YeldF','ZeroSwapLabs',
            'ZKSwapOfficial','zytarahq']
followers2 = []

#print(user_info)
for id in id_list2:
    try:
        user_info = api.get_user(id)._json
        follower = user_info['followers_count']
        followers2.append(follower)
    except Exception as e:
        followers2.append('na')
    continue
print (id_list2) #optional
print (followers2)

['autofarmnetwork', 'bDollar_Fi', 'beefyfinance', 'bitgrit_global', 'bloqinc', 'BondlyFinance', 'CafeSwapFinance', 'crowfinance', 'Crypto_novae', 'dao_duck', 'DeFi_Absorber', 'deflectprotocol', 'ethalend', 'ezDeFi', 'FinanceGoose', 'flarefinance', 'goldfinch_fi', 'InverseProject', 'Kylin_Network', 'Liquid_Global', 'marginswap', 'Mdextech', 'mimoprotocol', 'NftHero', 'overlinenetwork', 'paid_network', 'PandaYield', 'QuiverX5', 'rigelprotocol', 'shadows_defi', 'sparkpointio', 'stakewise_io', 'Team_Hedget', 'TheDaoMaker', 'tixlfinance', 'UnidoEP', 'UNNFinance', 'unstoppableweb', 'xdefilab', 'xendfinance', 'YeldF', 'ZeroSwapLabs', 'ZKSwapOfficial', 'zytarahq']
[8764, 3995, 41386, 516, 7279, 19169, 4182, 4672, 7485, 31464, 1750, 936, 5658, 2428, 3197, 882, 2572, 5409, 17508, 28784, 896, 3004, 1798, 560, 9651, 35508, 2084, 7827, 6004, 16511, 46032, 605, 6819, 41937, 13601, 29927, 7498, 161398, 12124, 13948, 4481, 11130, 5854, 4157]

In [7]:
dict2 = {'id' : id_list, 'followers' : followers}
df2_twitter = pd.DataFrame(dict2)
df2_twitter

                 id  followers
0   autofarmnetwork       8764
1        bDollar_Fi       3995
2      beefyfinance      41386
3    bitgrit_global        516
4           bloqinc       7279
5     BondlyFinance      19169
6   CafeSwapFinance       4182
7       crowfinance       4672
8      Crypto_novae       7485
9          dao_duck      31464
10    DeFi_Absorber       1750
11  deflectprotocol        936
12         ethalend       5658
13           ezDeFi       2428
14     FinanceGoose       3197
15     flarefinance        882
16     goldfinch_fi       2572
17   InverseProject       5409
18    Kylin_Network      17508
19    Liquid_Global      28784
20       marginswap        896
21         Mdextech       3004
22     mimoprotocol       1798
23          NftHero        560
24  overlinenetwork       9651
25     paid_network      35508
26       PandaYield       2084
27         QuiverX5       7827
28    rigelprotocol       6004
29     shadows_defi      16511
30     sparkpointio      46032
31     stakewise_io        605
32      Team_Hedget       6819
33      TheDaoMaker      41937
34      tixlfinance      13601
35          UnidoEP      29927
36       UNNFinance       7498
37   unstoppableweb     161398
38         xdefilab      12124
39      xendfinance      13948
40            YeldF       4481
41     ZeroSwapLabs      11130
42   ZKSwapOfficial       5854
43         zytarahq       4157

In [ ]:
#end